node {
    def server = Artifactory.server('fabriciouehara')
    def rtGradle = Artifactory.newGradleBuild()
    def buildInfo = Artifactory.newBuildInfo()
    stage 'Build'
        git url: 'https://github.com/fabriciouehara/gs-gradle.git'
}
